# Site settings
title: Gabriele Angeletti
email: angeletti.gabriele@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My blog about Artificial Intelligence, Machine Learning and related topics.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.gabrieleangeletti.com" # the base hostname & protocol for your site
twitter_username: gabrieleang
github_username:  blackecho
google_play:
google_plus_com:   # Community link
google_plus_per: '+GabrieleAngeletti'  #Personal link
facebook_app_id: 1213455035336203

# Layout settings
header_type: default  # values [ drawer, default ]
post_type: highlight    # values [ highlight, default ]
pagination_type: ops  # values [ ops, default ]

more_vert:
  option1:
    name: Medium
    link: https://medium.com/@gabrieleang
  option2:
    name: Quora
    link: https://www.quora.com/profile/Gabriele-Angeletti
  option3:
    name: LinkedIn
    link: https://www.linkedin.com/in/gabriele-angeletti-71959a63

disqus: true
disqus_shortname: 'gabrieleangeletti'

# Build settings
markdown: kramdown
